/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.lfr.developer.models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class HardwareConfiguration extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -776687528818862974L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HardwareConfiguration\",\"namespace\":\"io.lfr.developer.models\",\"fields\":[{\"name\":\"cpu\",\"type\":{\"type\":\"double\",\"scale\":2}},{\"name\":\"memory\",\"type\":\"int\"},{\"name\":\"disk\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<HardwareConfiguration> ENCODER =
      new BinaryMessageEncoder<HardwareConfiguration>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<HardwareConfiguration> DECODER =
      new BinaryMessageDecoder<HardwareConfiguration>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<HardwareConfiguration> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<HardwareConfiguration> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<HardwareConfiguration> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<HardwareConfiguration>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this HardwareConfiguration to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a HardwareConfiguration from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a HardwareConfiguration instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static HardwareConfiguration fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private double cpu;
  private int memory;
  private long disk;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public HardwareConfiguration() {}

  /**
   * All-args constructor.
   * @param cpu The new value for cpu
   * @param memory The new value for memory
   * @param disk The new value for disk
   */
  public HardwareConfiguration(java.lang.Double cpu, java.lang.Integer memory, java.lang.Long disk) {
    this.cpu = cpu;
    this.memory = memory;
    this.disk = disk;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cpu;
    case 1: return memory;
    case 2: return disk;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cpu = (java.lang.Double)value$; break;
    case 1: memory = (java.lang.Integer)value$; break;
    case 2: disk = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'cpu' field.
   * @return The value of the 'cpu' field.
   */
  public double getCpu() {
    return cpu;
  }


  /**
   * Sets the value of the 'cpu' field.
   * @param value the value to set.
   */
  public void setCpu(double value) {
    this.cpu = value;
  }

  /**
   * Gets the value of the 'memory' field.
   * @return The value of the 'memory' field.
   */
  public int getMemory() {
    return memory;
  }


  /**
   * Sets the value of the 'memory' field.
   * @param value the value to set.
   */
  public void setMemory(int value) {
    this.memory = value;
  }

  /**
   * Gets the value of the 'disk' field.
   * @return The value of the 'disk' field.
   */
  public long getDisk() {
    return disk;
  }


  /**
   * Sets the value of the 'disk' field.
   * @param value the value to set.
   */
  public void setDisk(long value) {
    this.disk = value;
  }

  /**
   * Creates a new HardwareConfiguration RecordBuilder.
   * @return A new HardwareConfiguration RecordBuilder
   */
  public static io.lfr.developer.models.HardwareConfiguration.Builder newBuilder() {
    return new io.lfr.developer.models.HardwareConfiguration.Builder();
  }

  /**
   * Creates a new HardwareConfiguration RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new HardwareConfiguration RecordBuilder
   */
  public static io.lfr.developer.models.HardwareConfiguration.Builder newBuilder(io.lfr.developer.models.HardwareConfiguration.Builder other) {
    if (other == null) {
      return new io.lfr.developer.models.HardwareConfiguration.Builder();
    } else {
      return new io.lfr.developer.models.HardwareConfiguration.Builder(other);
    }
  }

  /**
   * Creates a new HardwareConfiguration RecordBuilder by copying an existing HardwareConfiguration instance.
   * @param other The existing instance to copy.
   * @return A new HardwareConfiguration RecordBuilder
   */
  public static io.lfr.developer.models.HardwareConfiguration.Builder newBuilder(io.lfr.developer.models.HardwareConfiguration other) {
    if (other == null) {
      return new io.lfr.developer.models.HardwareConfiguration.Builder();
    } else {
      return new io.lfr.developer.models.HardwareConfiguration.Builder(other);
    }
  }

  /**
   * RecordBuilder for HardwareConfiguration instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HardwareConfiguration>
    implements org.apache.avro.data.RecordBuilder<HardwareConfiguration> {

    private double cpu;
    private int memory;
    private long disk;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.lfr.developer.models.HardwareConfiguration.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cpu)) {
        this.cpu = data().deepCopy(fields()[0].schema(), other.cpu);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.memory)) {
        this.memory = data().deepCopy(fields()[1].schema(), other.memory);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.disk)) {
        this.disk = data().deepCopy(fields()[2].schema(), other.disk);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing HardwareConfiguration instance
     * @param other The existing instance to copy.
     */
    private Builder(io.lfr.developer.models.HardwareConfiguration other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.cpu)) {
        this.cpu = data().deepCopy(fields()[0].schema(), other.cpu);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.memory)) {
        this.memory = data().deepCopy(fields()[1].schema(), other.memory);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.disk)) {
        this.disk = data().deepCopy(fields()[2].schema(), other.disk);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'cpu' field.
      * @return The value.
      */
    public double getCpu() {
      return cpu;
    }


    /**
      * Sets the value of the 'cpu' field.
      * @param value The value of 'cpu'.
      * @return This builder.
      */
    public io.lfr.developer.models.HardwareConfiguration.Builder setCpu(double value) {
      validate(fields()[0], value);
      this.cpu = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'cpu' field has been set.
      * @return True if the 'cpu' field has been set, false otherwise.
      */
    public boolean hasCpu() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'cpu' field.
      * @return This builder.
      */
    public io.lfr.developer.models.HardwareConfiguration.Builder clearCpu() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'memory' field.
      * @return The value.
      */
    public int getMemory() {
      return memory;
    }


    /**
      * Sets the value of the 'memory' field.
      * @param value The value of 'memory'.
      * @return This builder.
      */
    public io.lfr.developer.models.HardwareConfiguration.Builder setMemory(int value) {
      validate(fields()[1], value);
      this.memory = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'memory' field has been set.
      * @return True if the 'memory' field has been set, false otherwise.
      */
    public boolean hasMemory() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'memory' field.
      * @return This builder.
      */
    public io.lfr.developer.models.HardwareConfiguration.Builder clearMemory() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'disk' field.
      * @return The value.
      */
    public long getDisk() {
      return disk;
    }


    /**
      * Sets the value of the 'disk' field.
      * @param value The value of 'disk'.
      * @return This builder.
      */
    public io.lfr.developer.models.HardwareConfiguration.Builder setDisk(long value) {
      validate(fields()[2], value);
      this.disk = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'disk' field has been set.
      * @return True if the 'disk' field has been set, false otherwise.
      */
    public boolean hasDisk() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'disk' field.
      * @return This builder.
      */
    public io.lfr.developer.models.HardwareConfiguration.Builder clearDisk() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public HardwareConfiguration build() {
      try {
        HardwareConfiguration record = new HardwareConfiguration();
        record.cpu = fieldSetFlags()[0] ? this.cpu : (java.lang.Double) defaultValue(fields()[0]);
        record.memory = fieldSetFlags()[1] ? this.memory : (java.lang.Integer) defaultValue(fields()[1]);
        record.disk = fieldSetFlags()[2] ? this.disk : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<HardwareConfiguration>
    WRITER$ = (org.apache.avro.io.DatumWriter<HardwareConfiguration>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<HardwareConfiguration>
    READER$ = (org.apache.avro.io.DatumReader<HardwareConfiguration>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeDouble(this.cpu);

    out.writeInt(this.memory);

    out.writeLong(this.disk);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.cpu = in.readDouble();

      this.memory = in.readInt();

      this.disk = in.readLong();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.cpu = in.readDouble();
          break;

        case 1:
          this.memory = in.readInt();
          break;

        case 2:
          this.disk = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










